### ISSUE TITLE
Sort Table by Column [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [sandwichfarm/nostr-watch#371]
**Is your feature request related to a problem? Please describe.**
No problem. New functionality.

**Describe the solution you'd like**
## User Story ##
As a nostr.watch user, who wants to see all e.g. paid relays first, I would like the ability to sort a column by values in both ascending, and descending order, so I can find the information I am looking for.

### Acceptance Criteria ###
1. User can sort by column. If user clicks sort by paid column status, sort in descending order. That is, all paid relays should be displayed first.
2. If user clicks again on sort by paid column status, sort in ascending order. That is, all unpaid relays should be displayed first.
3. User can disable sorting.

**Describe alternatives you've considered**
Filtering functionality could also work. See #198.

**Additional context**

**Comment by dskvr** [comment]
Hey @alltheseas,

Your user story has already been satiated via aggregates, but not via sorting. 
https://next.nostr.watch/relays/find

![Screen Shot 2023-02-10 at 5 15 50 PM](https://user-images.githubusercontent.com/299465/218141297-eee7c9a1-0670-4681-803b-b30912b8cd7f.png)

For the acceptance criteria, at least for the examples given items 1-3 are already partially met

> User can sort by column. If user clicks sort by paid column status, sort in descending order. That is, all paid relays should be displayed first.

(screenshot above)

> If user clicks again on sort by paid column status, sort in ascending order. That is, all unpaid relays should be displayed first.

This is not implemented, would require a "free" aggregate, and then things get confusing. Need to think about this more. 

> User can disable sorting.

![Screen Shot 2023-02-10 at 5 20 40 PM](https://user-images.githubusercontent.com/299465/218142343-4b10eff9-f95f-44cb-a0ba-037730c33d1d.png)

> Filtering functionality could also work. See https://github.com/dskvr/nostr-watch/issues/198.

I can add this to filters instead of as an aggregate, but aggregate seems more appropriate and has some UX advantages (not buried). 

Regarding sorting by columns, there was an old issue (#47) but was closed due to higher priorities, and didn't directly address your request. This particular feature would need to wait until a code-cleanup to prevent the addition of insurmountable technical debt, and I would really prefer not to lock-in to a datatable library quite yet, as generally a lot of control is lost. 

Should I interpret this issue as primarily requesting the ability to sort by column header?

**Comment by dskvr** [comment]
> Yes

Great! Thanks for the issue. I would estimate this will make it into a release between 4-8 weeks. Reason being, is that the next alpha release is focused around providing data and nudging relay operators, as opposed to being user-focused.
