### ISSUE TITLE
pubKey invalid

### ISSUE THREAD

**Issue by pfergi42** [sandwichfarm/nostr-watch#492]
**Describe the bug**
nostr.watch returning error but pubkey is in hex:
`"pubkeyError": "pubkey is in npub format, should be hex",`

**To Reproduce**
1. navigate to: https://nostr.watch/relay/nostr.azte.co
2. expand results and go to very bottom

**Expected behavior**
pubkey is valid, so would expect it to confirm

**Screenshots**
![1](https://user-images.githubusercontent.com/4021240/224136157-e6a5589e-0a52-41b0-a366-5a5985565719.png)

![2](https://user-images.githubusercontent.com/4021240/224136181-57f98e3a-17cc-47fe-a35d-0682a3c943d2.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: chrome

**Comment by dskvr** [comment]
I am not able to replicate, but I have a feeling the issue you are seeing is happening because pubkeyError is only set if there's an error, when the results are merged, the error is still there (in localStorage). Instead, I'll always set pubkeyError as a blank string so that subsequent checks will overwrite old results.

**Comment by pfergi42** [comment]
Thanks! How often is production updated?

**Comment by dskvr** [comment]
Usually very frequently, but I haven't had the opportunity to push these changes because I'm I have been preparing for other things.
