### ISSUE TITLE
Cannot filter by NIP

### ISSUE THREAD

**Issue by mplorentz** [sandwichfarm/nostr-watch#677]
**Describe the bug**
I can no longer see the filters to filter something by NIP, software, etc.

**To Reproduce**
1. Open https://nostr.watch/relays/find 

**Expected behavior**
I can filter the listed relays by the NIPs they support

**Screenshots**
![Screenshot 2024-07-24 at 3 58 02 PM](https://github.com/user-attachments/assets/503a0c74-1be7-4d66-b7e1-b7629461b51d)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 128

**Additional context**
Thanks for hosting this awesome free service! It is super useful for me as a client dev.

**Comment by dskvr** [comment]
@mplorentz Filters aren't visible when the data is still being populated. At the top right corner there should be a status indicator. When data is populated, the filters will reappear. If the status is never finishing, or is taking a long time, it's possible your GUI is stuck in 'client-side testing` mode. Click the gear to go to preferences and uncheck 'client-side testing'

Go back to the homepage, and after 5-10 seconds the filters should be there. Otherwise, send me the developer console output.

<img width="1442" alt="Screen Shot 2024-07-26 at 10 00 04 PM" src="https://github.com/user-attachments/assets/a7c3ceff-27ec-49ab-99dd-0ea1534048e7">

**Comment by mplorentz** [comment]
Hm ok. I went to give it another try but now I just get a blank white screen. I see these errors in the console:
```
The resource from “https://nostr.watch/chunk-vendors.0b78ebee1f1ae755.bundle.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[nostr.watch](https://nostr.watch/)
The resource from “https://nostr.watch/app.0b78ebee1f1ae755.bundle.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by dskvr** [comment]
Did you trying clearing the cache from preferences page?

**Comment by mplorentz** [comment]
Thank you! Clearing my browser cache and leaving the page open allowed me to enable the filters again. Thanks for your work on nostr.watch. It's a tool that comes in handy often as a client dev!

**Comment by dskvr** [comment]
No problem! Thanks for the kind words and moral support. I'll keep you in the loop for beta testing on the next version.
